import { useMemo } from 'react';
import katex from 'katex';

/**
 * Render a string containing a mix of plain text and LaTeX math.
 * - $...$   -> inline math
 * - $$...$$ -> block math
 * Malformed LaTeX is shown as-is in red rather than crashing.
 * KaTeX runs with trust:false (no \href/\includegraphics) for safety.
 */
function renderSegment(segment, displayMode, key) {
  try {
    const html = katex.renderToString(segment, {
      displayMode,
      throwOnError: false, // KaTeX renders an error node instead of throwing
      trust: false,
      strict: 'ignore'
    });
    return (
      <span
        key={key}
        // KaTeX output is generated by KaTeX itself, not user HTML.
        dangerouslySetInnerHTML={{ __html: html }}
      />
    );
  } catch {
    // Belt-and-suspenders: if KaTeX still throws, show the raw source.
    return (
      <span key={key} className="text-destructive">
        {displayMode ? `$$${segment}$$` : `$${segment}$`}
      </span>
    );
  }
}

/**
 * Split text into plain/inline/block segments and render each.
 * Tokenizes on $$...$$ first, then $...$ within the remaining text.
 */
function parse(content) {
  const nodes = [];
  let key = 0;

  // Split on block math first.
  const blockParts = content.split(/(\$\$[^$]*\$\$)/g);

  for (const part of blockParts) {
    if (part.startsWith('$$') && part.endsWith('$$') && part.length >= 4) {
      nodes.push(renderSegment(part.slice(2, -2), true, key++));
      continue;
    }

    // Within non-block text, split on inline math.
    const inlineParts = part.split(/(\$[^$]*\$)/g);
    for (const seg of inlineParts) {
      if (seg.startsWith('$') && seg.endsWith('$') && seg.length >= 2) {
        nodes.push(renderSegment(seg.slice(1, -1), false, key++));
      } else if (seg.length > 0) {
        // Plain text — React escapes this automatically (XSS-safe).
        nodes.push(<span key={key++}>{seg}</span>);
      }
    }
  }

  return nodes;
}

export function LatexRenderer({ content = '', className }) {
  const nodes = useMemo(() => parse(content), [content]);

  if (!content) {
    return <span className="italic text-muted-foreground/60">(empty)</span>;
  }

  return <span className={className}>{nodes}</span>;
}
